tareas/config/routes.rb
Rails.application.routes.draw do
  resources :homeworks
  resources :deletes
  resources :homeworks

  root 'homeworks#index'

end

tareas/app/models/delete.rb
class Delete < ActiveRecord::Base
end

tareas/app/models/homework.rb
class Homework < ActiveRecord::Base
end

tareas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

tareas/app/controllers/deletes_controller.rb
class DeletesController < ApplicationController
  before_action :set_delete, only: [:show, :edit, :update, :destroy]

  # GET /deletes
  # GET /deletes.json
  def index
    @deletes = Delete.all
  end

  # GET /deletes/1
  # GET /deletes/1.json
  def show
  end

  # GET /deletes/new
  def new
    @delete = Delete.new
  end

  # GET /deletes/1/edit
  def edit
  end

  # POST /deletes
  # POST /deletes.json
  def create
    @delete = Delete.new(delete_params)

    respond_to do |format|
      if @delete.save
        format.html { redirect_to @delete, notice: 'Delete was successfully created.' }
        format.json { render :show, status: :created, location: @delete }
      else
        format.html { render :new }
        format.json { render json: @delete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deletes/1
  # PATCH/PUT /deletes/1.json
  def update
    respond_to do |format|
      if @delete.update(delete_params)
        format.html { redirect_to @delete, notice: 'Delete was successfully updated.' }
        format.json { render :show, status: :ok, location: @delete }
      else
        format.html { render :edit }
        format.json { render json: @delete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deletes/1
  # DELETE /deletes/1.json
  def destroy
    @delete.destroy
    respond_to do |format|
      format.html { redirect_to deletes_url, notice: 'Delete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delete
      @delete = Delete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delete_params
      params.require(:delete).permit(:homework)
    end
end

tareas/app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy]

  # GET /homeworks
  # GET /homeworks.json
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = Homework.new(homework_params)

    respond_to do |format|
      if @homework.save
        format.html { redirect_to @homework, notice: 'Homework was successfully created.' }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: 'Homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: 'Homework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_params
      params.require(:homework).permit(:materia, :tiempo, :nombre, :observaciones)
    end
end

tareas/app/helpers/application_helper.rb
module ApplicationHelper
end

tareas/app/helpers/deletes_helper.rb
module DeletesHelper
end

tareas/app/helpers/homeworks_helper.rb
module HomeworksHelper
end

tareas/app/views/deletes/_form.html.erb
<%= form_for(@delete) do |f| %>
  <% if @delete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@delete.errors.count, "error") %> prohibited this delete from being saved:</h2>

      <ul>
      <% @delete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :homework %><br>
    <%= f.text_field :homework %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tareas/app/views/deletes/edit.html.erb
<h1>Editing Delete</h1>

<%= render 'form' %>

<%= link_to 'Show', @delete %> |
<%= link_to 'Back', deletes_path %>

tareas/app/views/deletes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Deletes</h1>

<table>
  <thead>
    <tr>
      <th>Homework</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deletes.each do |delete| %>
      <tr>
        <td><%= delete.homework %></td>
        <td><%= link_to 'Show', delete %></td>
        <td><%= link_to 'Edit', edit_delete_path(delete) %></td>
        <td><%= link_to 'Destroy', delete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delete', new_delete_path %>

tareas/app/views/deletes/new.html.erb
<h1>New Delete</h1>

<%= render 'form' %>

<%= link_to 'Back', deletes_path %>

tareas/app/views/deletes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Homework:</strong>
  <%= @delete.homework %>
</p>

<%= link_to 'Edit', edit_delete_path(@delete) %> |
<%= link_to 'Back', deletes_path %>

tareas/app/views/homeworks/_form.html.erb
<%= form_for(@homework) do |f| %>
  <% if @homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
      <% @homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :materia %><br>
    <%= f.text_field :materia %>
  </div>
  <div class="field">
    <%= f.label :tiempo %><br>
    <%= f.number_field :tiempo %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :observaciones %><br>
    <%= f.text_field :observaciones %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tareas/app/views/homeworks/edit.html.erb
<h1>Editing Homework</h1>

<%= render 'form' %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

tareas/app/views/homeworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Homeworks</h1>

<table>
  <thead>
    <tr>
      <th>Materia</th>
      <th>Tiempo</th>
      <th>Nombre</th>
      <th>Observaciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= homework.materia %></td>
        <td><%= homework.tiempo %></td>
        <td><%= homework.nombre %></td>
        <td><%= homework.observaciones %></td>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>

tareas/app/views/homeworks/new.html.erb
<h1>New Homework</h1>

<%= render 'form' %>

<%= link_to 'Back', homeworks_path %>

tareas/app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Materia:</strong>
  <%= @homework.materia %>
</p>

<p>
  <strong>Tiempo:</strong>
  <%= @homework.tiempo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @homework.nombre %>
</p>

<p>
  <strong>Observaciones:</strong>
  <%= @homework.observaciones %>
</p>

<%= link_to 'Edit', edit_homework_path(@homework) %> |
<%= link_to 'Back', homeworks_path %>

tareas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tareas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>